"""
pulumi_provider.py — Pulumi IaC Provider for ankavm VMs
ankavm v2.5.10 Cloud/K8s

Features:
  - generate_pulumi_program(vms, language) — TypeScript or Python Pulumi program
  - export_state() — current VM state as Pulumi-compatible JSON
  - get_provider_schema() — ankavm Pulumi provider schema

Config persisted to /var/lib/ankavm/pulumi_state.json
No external dependencies (stdlib + subprocess only). No periodic background jobs.
"""

from __future__ import annotations
import json
import logging
import subprocess
import threading
import time
from pathlib import Path
from typing import Optional

log = logging.getLogger("pulumi_provider")

_STATE_FILE = Path("/var/lib/ankavm/pulumi_state.json")
_lock       = threading.Lock()


# ── Persistent store ──────────────────────────────────────────────────────────

def _load() -> dict:
    try:
        if _STATE_FILE.exists():
            return json.loads(_STATE_FILE.read_text(encoding="utf-8"))
    except Exception as e:
        log.warning("pulumi_provider load fail: %s", e)
    return {"deployments": [], "last_export": None}


def _save(data: dict) -> None:
    try:
        _STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
        tmp = _STATE_FILE.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(data, indent=2), encoding="utf-8")
        tmp.replace(_STATE_FILE)
    except Exception as e:
        log.warning("pulumi_provider save fail: %s", e)


# ── VM data helpers ───────────────────────────────────────────────────────────

def _get_vms_from_system() -> list:
    """Read VM list via virsh if available, else return empty list."""
    try:
        r = subprocess.run(
            ["virsh", "list", "--all", "--name"],
            capture_output=True, text=True, timeout=10
        )
        if r.returncode == 0:
            names = [n.strip() for n in r.stdout.splitlines() if n.strip()]
            vms = []
            for name in names:
                vms.append({"id": name, "name": name, "memory_mb": 1024, "vcpus": 1})
            return vms
    except Exception:
        pass
    return []


# ── Public API ────────────────────────────────────────────────────────────────

def generate_pulumi_program(vms: Optional[list] = None, language: str = "typescript") -> dict:
    """Generate a Pulumi program for the given VM list.

    Args:
        vms: List of VM dicts with keys: id, name, memory_mb, vcpus.
             If None, reads from the system via virsh.
        language: 'typescript' or 'python'

    Returns:
        dict with keys: language, code, filename, count
    """
    if vms is None:
        vms = _get_vms_from_system()

    if language == "python":
        lines = [
            '"""ankavm VM infrastructure — generated by ankavm Pulumi Provider."""',
            "import pulumi",
            "import pulumi_ankavm as ankavm",
            "",
        ]
        for vm in vms:
            vid   = str(vm.get("id", "vm")).replace("-", "_").replace(".", "_")
            name  = vm.get("name", vm.get("id", "vm"))
            mem   = vm.get("memory_mb", 1024)
            cpus  = vm.get("vcpus", 1)
            lines += [
                f'{vid} = ankavm.VirtualMachine("{name}",',
                f'    memory_mb={mem},',
                f'    vcpus={cpus},',
                f')',
                f'pulumi.export("{vid}_id", {vid}.id)',
                "",
            ]
        code     = "\n".join(lines)
        filename = "infra/__main__.py"
    else:
        # TypeScript (default)
        lines = [
            '// ankavm VM infrastructure — generated by ankavm Pulumi Provider.',
            'import * as pulumi from "@pulumi/pulumi";',
            'import * as ankavm from "@pulumi/ankavm";',
            "",
        ]
        for vm in vms:
            vid   = str(vm.get("id", "vm")).replace("-", "_").replace(".", "_")
            name  = vm.get("name", vm.get("id", "vm"))
            mem   = vm.get("memory_mb", 1024)
            cpus  = vm.get("vcpus", 1)
            lines += [
                f'const {vid} = new ankavm.VirtualMachine("{name}", {{',
                f'    memoryMb: {mem},',
                f'    vcpus: {cpus},',
                f'}});',
                f'export const {vid}Id = {vid}.id;',
                "",
            ]
        code     = "\n".join(lines)
        filename = "infra/index.ts"

    log.info("pulumi program generated: language=%s vms=%d", language, len(vms))
    return {
        "language": language,
        "code":     code,
        "filename": filename,
        "count":    len(vms),
    }


def export_state() -> dict:
    """Export current system VM state as Pulumi-compatible state JSON."""
    vms = _get_vms_from_system()
    resources = []
    for vm in vms:
        resources.append({
            "urn":    f"urn:pulumi:dev::ankavm::ankavm:index:VirtualMachine::{vm['name']}",
            "type":   "ankavm:index:VirtualMachine",
            "id":     vm["id"],
            "inputs": {
                "name":      vm["name"],
                "memory_mb": vm.get("memory_mb", 1024),
                "vcpus":     vm.get("vcpus", 1),
            },
            "outputs": {
                "id":   vm["id"],
                "name": vm["name"],
            },
        })

    state = {
        "version": 3,
        "checkpoint": {
            "stack":   "dev",
            "config":  {},
            "latest": {
                "manifest": {
                    "time":    time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "magic":   "0xware-pulumi-state",
                    "version": "v3.0.0",
                },
                "resources": resources,
            },
        },
    }

    with _lock:
        data = _load()
        data["last_export"] = time.time()
        _save(data)

    log.info("pulumi state exported: %d resources", len(resources))
    return state


def get_provider_schema() -> dict:
    """Return ankavm Pulumi provider JSON schema."""
    return {
        "name":        "ankavm",
        "version":     "2.5.10",
        "description": "ankavm KVM Hypervisor Pulumi Provider",
        "resources": {
            "ankavm:index:VirtualMachine": {
                "description": "An ankavm KVM Virtual Machine",
                "inputs": {
                    "name":        {"type": "string", "description": "VM name"},
                    "memory_mb":   {"type": "integer", "description": "RAM in MB", "default": 1024},
                    "vcpus":       {"type": "integer", "description": "vCPU count", "default": 1},
                    "disk_gb":     {"type": "integer", "description": "Root disk size in GB", "default": 20},
                    "os_image":    {"type": "string",  "description": "Cloud image path or URL"},
                    "network":     {"type": "string",  "description": "Network bridge name", "default": "virbr0"},
                    "cloud_init":  {"type": "object",  "description": "Cloud-init user-data map"},
                },
                "outputs": {
                    "id":         {"type": "string"},
                    "name":       {"type": "string"},
                    "ip_address": {"type": "string"},
                    "state":      {"type": "string"},
                },
            },
            "ankavm:index:Network": {
                "description": "An ankavm virtual network",
                "inputs": {
                    "name":    {"type": "string", "description": "Network name"},
                    "cidr":    {"type": "string", "description": "IPv4 CIDR"},
                    "vlan_id": {"type": "integer", "description": "VLAN tag (optional)"},
                    "dhcp":    {"type": "boolean", "description": "Enable DHCP", "default": True},
                },
                "outputs": {
                    "id":     {"type": "string"},
                    "bridge": {"type": "string"},
                },
            },
        },
        "functions": {
            "ankavm:index:listVMs": {
                "description": "List all VMs managed by ankavm",
                "outputs": {
                    "vms": {"type": "array", "items": {"type": "object"}},
                },
            },
        },
    }






